const games = [
    {
        id: 1,
        title: "PUBG:BATTLEGROUNDS",
        releasedate: '17.12.21',
        price: 29000,
        playtype: ['nintendo', 'playstation', 'pc'],
        tag: ['Survival', 'FPS', 'Multiplayer', 'TPS', 'Action', 'Cooperative', 'PvP'],
        isChecked: false,
        src_title: "/images/storedetails/title1.jpg",
        detailscontent: "PUBG:배틀그라운드는 최대 100인의 플레이어가 다양한 무기와 전략으로 마지막 1명이 살아남는 순간까지 전투하는 배틀로얄 게임입니다. 점점 좁혀지는 경기 구역내에서 전략적으로 배치된 무기, 차량 및 소모품을 찾아 전투하고 '최후의 1인'이 되어보세요.",
        src_detail1: "/images/storedetails/detail1-1.jpg",
        detail1_name: "SOLO MODE",
        detail1_content: "1인 전투입니다. 오로지 나만의 힘으로 짜릿한 승리를 경험할 수 있습니다.",
        src_detail2: "/images/storedetails/detail1-2.jpg",
        detail2_name: "DUO MODE",
        detail2_content: "최대 2인이 팀을 이룹니다. 친구를 초대해 한 팀으로 긴밀한 협동 플레이를 해보세요.",
        src_detail3: "/images/storedetails/detail1-3.jpg",
        detail3_name: "SQUAD MODE",
        detail3_content: "최대 4인이 함께 합니다. 팀의 전략에 맞춰 상황에 맞는 전술이 가능합니다.",
        OS: ["Windows 10 (64 bit)", 'Windows 10 (64 bit)'],
        Processor: ['Intel Core i5-4430 / AMD FX-6300', ' Intel Core i5-6600K / AMD Ryzen 5 1600'],
        Memory: ['8 GB RAM', '16 GB RAM'],
        Graphics: ['NVIDIA GeForce GTX 960 2GB / AMD', ' NVIDIA GeForce GTX 1060 3GB / AMD'],
        DirectX: ["Version 11", 'Version 11'],
        Storage: "6 GB available space",
        SoundCard: "DirectX 9.0c Compliant"
    },
    {
        id: 2,
        title: "Apex Legends",
        releasedate: '24.06.21',
        price: 39000,
        playtype: ['playstation', 'pc'],
        tag: ['Survival', 'FPS', 'Multiplayer', 'Action', 'Cooperative', 'PvP'],
        isChecked: false,
        src_title: "/images/storedetails/title2.jpg",
        detailscontent: "빠른 페이스의 팀 기반 배틀로얄 게임으로, 전략적 플레이와 개성 넘치는 캐릭터들이 돋보입니다. 플레이어는 다양한 능력을 가진 전설적인 영웅 중 하나를 선택하여 팀과 함께 승리를 위해 싸워보세요!",
        src_detail1: "/images/storedetails/detail2-1.jpg",
        detail1_name: "Battle Royale",
        detail1_content: "20개 팀이 지도에서 생존을 위해 싸우는 대규모 전투 모드입니다.",
        src_detail2: "/images/storedetails/detail2-2.jpg",
        detail2_name: "Arenas",
        detail2_content: "3v3 팀이 라운드 기반 전투를 통해 상대 팀을 전멸시키는 소규모 집중 전투 모드입니다.",
        src_detail3: "/images/storedetails/detail2-3.jpg",
        detail3_name: "Limited-Time Event",
        detail3_content: "특정 기간 동안만 제공되는 특별한 게임 모드로, 기존의 배틀 로얄이나 아레나와는 다른 독특한 규칙과 테마를 가집니다."
    },
    {
        id: 3,
        title: "GTFO",
        releasedate: '24.06.21',
        price: 49900,
        playtype: ['pc'],
        tag: ['Survival', 'FPS', 'Multiplayer', 'TPS', 'Action', 'Cooperative', 'Horror'],
        isChecked: false,
        src_title: "/images/storedetails/title3.jpg",
        detailscontent: "협동 중심의 1인칭 생존 공포 게임으로, 플레이어들은 팀을 이뤄 절망적인 환경에서 위험한 임무를 수행합니다. 높은 난이도와 긴장감 넘치는 분위기로 강력한 팀워크와 전략이 요구됩니다.",
        src_detail1: "/images/storedetails/detail3-1.jpg",
        detail1_name: "Expedition Mode",
        detail1_content: "플레이어들은 팀을 이루어 복잡한 지하 시설을 탐험하며 미션을 수행합니다. 높은 난이도와 전략적 협력이 요구됩니다.",
        src_detail2: "/images/storedetails/detail3-2.jpg",
        detail2_name: "Rundown Mode",
        detail2_content: "일정 기간 동안 사용할 수 있는 미션 목록으로, 업데이트마다 새로운 미션과 도전 과제가 추가되어 플레이어는 다양한 미션을 경험하며 끊임없이 변화하는 콘텐츠를 즐길 수 있습니다.",
        src_detail3: "/images/storedetails/detail3-3.jpg",
        detail3_name: "Custom Mode",
        detail3_content: "플레이어가 미션 설정을 변경하고 자신만의 게임 환경을 만들 수 있는 모드로, 난이도와 적의 배치를 조정하여 다양한 플레이 스타일을 체험할 수 있습니다."
    },
    {
        id: 4,
        title: "Terraria",
        releasedate: '24.06.21',
        price: 11000,
        playtype: ['pc'],
        tag: ['Survival', 'Multiplayer', 'Action', 'Cooperative', 'RPG', 'Adventure'],
        isChecked: false,
        src_title: "/images/storedetails/title4.jpg",
        detailscontent: "2D 샌드박스 어드벤처 게임으로, 채굴, 건축, 전투 등 다양한 활동을 통해 무한한 탐험과 창작의 재미를 제공합니다. 다양한 몬스터와 보스를 물리치고 자원을 모아 자신만의 세상을 만들어 나가는 것이 주요 목표입니다."
    },

    {
        id: 5,
        title: "World War Z",
        releasedate: '24.06.21',
        price: 32000,
        playtype: ['playstation', 'pc'],
        tag: ['Survival', 'FPS', 'Multiplayer', 'TPS', 'Action', 'Cooperative', 'Zombies', 'Horror'],
        isChecked: false,
        src_title: "/images/storedetails/title5.jpg",
        detailscontent: "빠르게 움직이는 좀비 무리를 상대하는 협동형 3인칭 슈팅 게임입니다. 플레이어는 전 세계 여러 도시를 배경으로 다양한 클래스와 무기를 사용해 생존을 목표로 하는 임무를 수행합니다."
    },
    {
        id: 6,
        title: "Overwatch2",
        releasedate: '24.06.21',
        price: 9800,
        playtype: ['pc'],
        tag: ['FPS', 'Multiplayer', 'Action', 'Cooperative', 'PvP'],
        isChecked: false,
        src_title: "/images/storedetails/title6.jpg",
        detailscontent: "팀 기반의 멀티플레이어 1인칭 슈팅 게임으로, 각기 다른 능력을 가진 영웅들로 팀을 구성해 목표를 달성하는 것이 핵심입니다. 새로운 게임 모드, 스토리 중심의 PvE 콘텐츠, 향상된 그래픽과 시스템으로 기존 Overwatch의 경험을 확장합니다."
    },
    {
        id: 7,
        title: "Grand Theft Auto V",
        releasedate: '24.06.21',
        price: 44000,
        playtype: ['playstation', 'pc'],
        tag: ['Multiplayer', 'Action', 'TPS', 'Cooperative', 'Adventure', 'Singleplayer'],
        isChecked: false,
        src_title: "/images/storedetails/title7.jpg",
        detailscontent: "오픈 월드 액션 어드벤처 게임으로, 세 명의 주인공을 중심으로 한 범죄와 스토리 중심의 플레이를 제공합니다. 로스 산토스라는 가상 도시에서 다양한 미션을 수행하고, 자유롭게 탐험하며, 온라인 멀티플레이 모드에서도 즐길 수 있습니다."
    },
    {
        id: 8,
        title: "Back 4 Blood",
        releasedate: '24.06.21',
        price: 68800,
        playtype: ['playstation', 'pc'],
        tag: ['Survival', 'FPS', 'Multiplayer', 'Action', 'Cooperative', 'Zombies', 'Horror', 'PvP'],
        isChecked: false,
        src_title: "/images/storedetails/title8.jpg",
        detailscontent: "좀비 아포칼립스를 배경으로 한 협동 1인칭 슈팅 게임으로, 플레이어들이 함께 팀을 이루어 강력한 적들과 싸우며 생존을 도모합니다. Left 4 Dead 시리즈의 정신적 후속작으로, 빠른 속도와 긴장감 넘치는 전투가 특징입니다."
    },
    {
        id: 9,
        title: "Diablo IV",
        releasedate: '24.06.21',
        price: 62400,
        playtype: ['pc'],
        tag: ['Multiplayer', 'Action', 'Cooperative', 'RPG', 'Singleplayer', 'Story'],
        isChecked: false,
        src_title: "/images/storedetails/title9.jpg",
        detailscontent: "어둡고 고딕한 세계를 배경으로 한 액션 RPG로, 다양한 클래스와 스킬을 활용해 악마들과 싸우며 이야기를 진행합니다. 방대한 오픈 월드와 깊이 있는 스토리, 강화된 멀티플레이 요소를 통해 깊이 있는 게임 플레이 경험을 제공합니다."
    },
    {
        id: 10,
        title: "Palworld",
        releasedate: '24.06.21',
        price: 32000,
        playtype: ['playstation', 'pc'],
        tag: ['Survival', 'Multiplayer', 'TPS', 'Action', 'Cooperative', 'RPG'],
        isChecked: false,
        src_title: "/images/storedetails/title10.jpg",
        detailscontent: "드넓은 세계에 서식하는 신비한 생물 '팰'을 수집하여 전투, 건축, 농업에 투입하거나 공장에서 일을 시키는 등, 전에 없던 새로운 체험을 선사하는 멀티 지원 오픈월드 서바이벌 크래프트 게임입니다."
    },
    {
        id: 11,
        title: "Overcooked! 2",
        releasedate: '24.06.21',
        price: 26000,
        playtype: ['nintendo', 'playstation', 'pc'],
        tag: ['Multiplayer', 'Action', 'Cooperative', 'Singleplayer', 'Cute', 'Simulation'],
        isChecked: false,
        src_title: "/images/storedetails/title11.jpg",
        detailscontent: "협동 요리 시뮬레이션 게임으로, 플레이어들이 팀을 이루어 다양한 주방에서 제한된 시간 내에 요리를 완성해야 합니다. 혼란스러운 주방 환경과 복잡한 레시피가 더해져 팀워크와 빠른 판단력이 요구됩니다."
    },
    {
        id: 12,
        title: "Super Bunny Man",
        releasedate: '24.06.21',
        price: 15250,
        playtype: ['pc'],
        tag: ['Multiplayer', 'Action', 'Cooperative', 'PvP', 'Cute'],
        isChecked: false
    },
    {
        id: 13,
        title: "Lovers in a Dangerous Spacetime",
        releasedate: '24.06.21',
        price: 16000,
        playtype: ['playstation', 'pc'],
        tag: ['Multiplayer', 'Action', 'Cooperative', 'Cute'],
        isChecked: false
    },
    {
        id: 14,
        title: "The Sims 4",
        releasedate: '24.06.21',
        price: 4900,
        playtype: ['playstation', 'pc'],
        tag: ['Multiplayer', 'Simulation', 'Cute'],
        isChecked: false
    },
    {
        id: 15,
        title: "Party Animals",
        releasedate: '24.06.21',
        price: 25900,
        playtype: ['nintendo', 'playstation', 'pc'],
        tag: ['Multiplayer', 'Action', 'Cooperative', 'PvP', 'Cute', 'Adventure'],
        isChecked: false
    },
    {
        id: 16,
        title: "Human Fall Flat",
        releasedate: '24.06.21',
        price: 20500,
        playtype: ['playstation', 'pc'],
        tag: ['Multiplayer', 'Action', 'Cooperative', 'Adventure', 'Singleplayer', 'Simulation'],
        isChecked: false
    },
    {
        id: 17,
        title: "Goose Goose Duck",
        releasedate: '24.06.21',
        price: 4900,
        playtype: ['pc'],
        tag: ['Multiplayer', 'Action', 'Cooperative', 'Cute', 'PvP'],
        isChecked: false
    },
    {
        id: 18,
        title: "Stardew Valley",
        releasedate: '24.06.21',
        price: 16000,
        playtype: ['nintendo', 'pc'],
        tag: ['Multiplayer', 'Simulation', 'Singleplayer', 'Cute'],
        isChecked: false
    },
    {
        id: 19,
        title: "Unrailed!",
        releasedate: '24.06.21',
        price: 24000,
        playtype: ['nintendo', 'pc'],
        tag: ['Multiplayer', 'Action', 'Cooperative', 'Cute', 'Survival'],
        isChecked: false
    },
    {
        id: 20,
        title: "Lethal Company",
        releasedate: '24.06.21',
        price: 11000,
        playtype: ['pc'],
        tag: ['Survival', 'Horror', 'Action', 'Aliens', 'Adventure'],
        isChecked: false
    },
    {
        id: 21,
        title: "PAYDAY 3",
        releasedate: '24.06.21',
        price: 40500,
        playtype: ['playstation', 'pc'],
        tag: ['FPS', 'Multiplayer', 'Action', 'Cooperative', 'RPG'],
        isChecked: false
    },
    {
        id: 22,
        title: "Eternal Return",
        releasedate: '24.06.21',
        price: 4900,
        playtype: ['playstation', 'pc'],
        tag: ['Survival', 'Multiplayer', 'Action', 'PvP'],
        isChecked: false
    },
    {
        id: 23,
        title: "Mario Party Superstars",
        releasedate: '21.10.29',
        price: 64800,
        playtype: ['nintendo'],
        tag: ['Multiplayer', 'Adventure', 'Cooperative'],
        isChecked: false
    },
    {
        id: 24,
        title: "Super Mario Bros.Wonder",
        releasedate: '23.10.20',
        price: 64800,
        playtype: ['nintendo'],
        tag: ['Multiplayer', 'Adventure', 'Cooperative'],
        isChecked: false
    },
    {
        id: 25,
        title: "Luigi's Mansion2 HD",
        releasedate: '24.06.27',
        price: 64800,
        playtype: ['nintendo'],
        tag: ['Multiplayer', 'Adventure', 'Cooperative'],
        isChecked: false
    },
    {
        id: 26,
        title: "Arise A Simple Story",
        releasedate: '20.12.04',
        price: 21500,
        playtype: ['nintendo', 'playstation', 'pc'],
        tag: ['Cute', 'Story'],
        isChecked: false,
        src_title: "/images/storedetails/title26.jpg",
        detailscontent: "사랑하는 연인을 잃는 슬픈 여행을 떠나보세요. 시간을 조작하고, 퍼즐을 풀며, 주변을 재구성해서 전생의 달콤 쌉쌀한 기억을 찾아 나가세요. 행복과 고난, 즐거움과 슬픔에 대한 이야기입니다. 우리 모두가 언젠가는 겪게 될 이야기죠.",
        src_detail1: "/images/storedetails/detail26-1.jpg",
        detail1_name: "Exploration",
        detail1_content: "각 챕터에서 환경을 더 자유롭게 탐험하며, 숨겨진 아이템과 비밀을 발견할 수 있습니다.",
        src_detail2: "/images/storedetails/detail26-2.jpg",
        detail2_name: "Time Manipulation",
        detail2_content: "게임 내에서 특정 구간에서 시간을 조작하여 퍼즐을 해결하고, 각 챕터에서 시간의 흐름을 제어하며 장애물을 극복할 수 있습니다.",
        src_detail3: "/images/storedetails/detail26-3.jpg",
        detail3_name: "Story",
        detail3_content: "주인공의 삶을 회상하며, 감동적인 스토리를 따라가며 퍼즐을 풀고 장애물을 극복하세요.",
        OS: ["Windows 10 (64 bit)", 'Windows 10 (64 bit)'],
        Processor: ['Intel Core i3 4340 3.6 GHz or AMD equivalent', ' Intel Core i7 3770K 3.5 GHz or AMD equivalent'],
        Memory: ['6 GB RAM', '8 GB RAM'],
        Graphics: ['NVIDIA GeForce GTX 670 2 GB or AMD Radeon equivalent', 'NVIDIA GeForce GTX 1060 6 GB or AMD Radeon equivalent'],
        DirectX: ["Version 11", 'Version 11'],
        Storage: "6 GB available space",
        SoundCard: "DirectX 9.0c Compliant"
    }
]


export default games;